apiVersion: pgv2.percona.com/v2
kind: PerconaPGCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: pg17
  finalizers:
  - percona.com/delete-pvc
  - percona.com/delete-ssl
spec:
  crVersion: 2.9.0

  image: docker.io/perconalab/percona-postgresql-operator:main-ppg17-postgres
  imagePullPolicy: Always
  postgresVersion: 17

  instances:
  - name: instance1
    replicas: 3
    resources:
      limits:
        cpu: 1.0
        memory: 2Gi
      requests:
        cpu: 1.0
        memory: 2Gi

    dataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

  proxy:
    pgBouncer:
      replicas: 3
      image: docker.io/perconalab/percona-postgresql-operator:main-pgbouncer17
      resources:
        limits:
          cpu: 1.0
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 128Mi
      expose:
        type: LoadBalancer

  backups:
    pgbackrest:
      image: docker.io/perconalab/percona-postgresql-operator:main-pgbackrest17
      manual:
        repoName: repo1
        options:
         - --type=full
      repos:
      - name: repo1
        schedules:
          full: "0 0 * * 6"
        volume:
          volumeClaimSpec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
  pmm:
    enabled: true
    image: docker.io/perconalab/pmm-client:dev-latest
    serverHost: monitoring-service
    secret: pmm-secret
